import csv
import glob
import logging
import math
import os
import shutil
import subprocess
import numpy as np

def load_vectors_from_files(vector_directory,profile_limit=None):
    """
    Load vectors and their corresponding identifiers from the given directory.
    """
    vectors_list = []
    identifiers = []  # List to store numeric identifiers
    # Collect all valid vector files
    vector_files = [f for f in os.listdir(vector_directory) if f.endswith('_vector.txt')]
    # Ensuring numeric sorting for consistency (e.g., ['1_vector.txt', '10_vector.txt', '2_vector.txt'] → sorted)
    vector_files.sort(key=lambda x: int(x.split('_')[0]))
 
    # Apply profile limit if specified
    if profile_limit:
        vector_files = vector_files[:profile_limit]
    for file_name in vector_files:
        file_path = os.path.join(vector_directory, file_name)
        with open(file_path, 'r') as file:
            vector_str = file.read().strip()
            try:
                vector = np.fromstring(vector_str, sep=' ')
                if vector.size > 0:  # Ensure it's not an empty vector
                    vectors_list.append(vector)

                    # Extract numeric identifier from file name
                    identifier = int(file_name.split('_')[0])
                    identifiers.append(identifier)
                else:
                    print(f"Warning: {file_name} contains an empty or invalid vector, skipping.")

            except ValueError:
                print(f"Error: Could not convert the content of {file_name} to a numpy array, skipping.")

    return vectors_list, identifiers


# When we instrument the mutant file and working with a mutant file we may lose the original file
# So we are having a backup of the file which we are replacing with a mutant file:
def backup_original_class_file(original_class_directory, className):
    className = f"{className}.class"
    original_class_file = os.path.join(original_class_directory, className)
    # Define the backup file path
    original_class_backup = original_class_file + ".backup"

    # Check if the backup already exists; if not, create it
    if not os.path.exists(original_class_backup):
        print("Creating a backup of the original class file.")
        shutil.copyfile(original_class_file, original_class_backup)
    else:
        print("Backup of the original class file already exists.")

    return original_class_backup


def generate_input_files(output_directory, number_of_files_to_generate, sentences_per_file, fuzzer,
                         subject_program):
    """
        Generating inputs as text files containing sentences generated by a fuzzer

        - Removing all existing files from the output directory to ensure it is clean before generating new files.
        - Re-creating the output directory to store the newly generated files.
        - Fuzzer may result in multiple sentences per fuzz due to the nature of the grammar rules
        (e.g., `stat+` in the grammar).
        - Appending "exit" command at the end of each file to signal the end.


        Example:
            generate_files("output_dir", 1000, 1, fuzzer)
            This will generate 1000 files, each with one sentence per file.
            :param fuzzer: Fuzzer instance used to generate sentences based on the grammar.
            :param sentences_per_file:The number of sentences to generate per file.
            :param subject_program: For which SUT program we are generating the INPUTS
            :param number_of_files_to_generate: The number of files to generate.
            :param output_directory: Directory where generated files will be saved.
        """
    # Remove all existing files from output directory
    if os.path.exists(output_directory):
        shutil.rmtree(output_directory)
    # Create new empty directory to re-generate input files
    os.makedirs(output_directory)

    # Config eof_marker: if we need to end the input with some specific keywords
    # depending on the subject program,
    # pass eof_marker depending on the subject program
    # - such as CALC need to add 'exit' end of the input file
    if subject_program == 'CALC':
        eof_marker = "exit"
    elif subject_program == 'basic':
        eof_marker = "bye"
    else:
        eof_marker = None

    # Generate files
    for file_number in range(1, number_of_files_to_generate + 1):
        # filename with number
        filename = os.path.join(output_directory, f"{file_number}.txt")
        with open(filename, "w") as f:
            # Generating sentences per file
            for _ in range(sentences_per_file):
                # Fuzzer will generate sometime more than one sentences : cause
                # in our grammar rule we have stat+
                f.write(fuzzer.fuzz())
                # Append the end-of-file marker if provided
            if eof_marker:
                f.write(f"\n{eof_marker}\n")


def instrument_classes(class_directory, instrument_class_directory):
    """
    Instruments the classes in the specified directory using JaCoCo CLI.
    N.B: When working with mutants :every time mutants will be replaced, the file would be again instrumented

        :param subject_program_name: The Name of the subject program will be used to check the package name
        :param instrument_class_directory:The directory where the instrumented classes will be saved.
        :param class_directory:The directory containing the classes to be instrumented.
    """
    # PACKAGE NAMING SHOULD BE DYNAMIC LATER >> FOR NOW WE ARE GUESSING WE KNOW ABOUT THE SUBJECT PROGRAMS
    # if subject_program_name == 'CALC':
    #     instrument_class_directory = instrument_class_directory  # no package
    # elif subject_program_name == 'basic':
    #     instrument_class_directory = os.path.join(instrument_class_directory, 'basic')  # /basic

    jacoco_path = 'COVERAGE_REPORTS/COVERAGE_TOOLS/Jacoco/jacococli.jar'
    # Check if the Instrumented directory exists
    if os.path.exists(instrument_class_directory):
        print(f"Directory {instrument_class_directory} exists. Removing it to re-instrument.")
        shutil.rmtree(instrument_class_directory)  # Remove the existing directory

    # Ensure the directory is created again after removal
    os.makedirs(instrument_class_directory, exist_ok=True)

    # Construct the command
    command = [
        "java", "-jar", jacoco_path,
        "instrument", class_directory,
        "--dest", instrument_class_directory  # have to check if they support package if they have any command
    ]
    # time out for the BASIC program when infinite loops

    # # Execute the command
    # subprocess.run(command)
    # Execute the command and capture the output for error handling
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error during instrumentation: {result.stderr}")
    else:
        print("Instrumentation successful.")
import re, random, pathlib

# Keywords / built-ins that should NOT be treated as user variables
_RESERVED = {
    "let", "print", "sum", "avg", "sin", "cos", "tan",
    "LET", "PRINT", "SUM", "AVG", "SIN", "COS", "TAN"
}

_ID_RE = re.compile(r"\b[a-zA-Z][a-zA-Z_0-9]*\b")  # JS-like identifiers
_LET_RE = re.compile(r"^\s*let\s+([a-zA-Z][a-zA-Z_0-9]*)\s*=\s*(.*)$",
                     re.IGNORECASE)

def calc_define_missing_variables(file_path: str, max_auto_defs: int = 5) -> None:
    """Prepend `Let X = N` for each variable used but never declared."""
    file_path = pathlib.Path(file_path)

    declared, used = set(), set()
    lines = file_path.read_text().splitlines(keepends=True)

    for line in lines:
        m = _LET_RE.match(line)
        if m:
            var, rhs = m.group(1), m.group(2)
            declared.add(var)
            used.update(t for t in _ID_RE.findall(rhs) if t not in _RESERVED)
        else:
            used.update(t for t in _ID_RE.findall(line) if t not in _RESERVED)

    missing = [v for v in used - declared]
    if len(missing) == 0:
        return  # nothing to do

    # Limit the auto-definitions to avoid huge preambles
    missing = missing[:max_auto_defs]

    new_defs = [f"let {v} = {random.randint(1, 99)}\n" for v in missing]

    # Avoid adding duplicates if script is re-run
    if lines and lines[0].startswith("let "):
        existing_header = [ln for ln in lines if ln.startswith("let ")]
        new_defs = [d for d in new_defs if d.split()[1] not in
                    {ln.split()[1] for ln in existing_header}]

    file_path.write_text("".join(new_defs + lines))






def modify_inputs_with_define_variable(folder_path, subject_program, file_prefix):
    """
    Applies subject-specific post-processing ONLY to files in the folder
    that match the given file_prefix.
    """
    # <<< Create a pattern to match files like 'fuzzingbook_probabilistic_1.txt', etc. >>>
    file_pattern = os.path.join(folder_path, f"{file_prefix}_*.txt")

    # <<< Use glob.glob to get a list of all files that match the pattern >>>
    files_to_process = glob.glob(file_pattern)

    print(f"Found {len(files_to_process)} files with prefix '{file_prefix}' to post-process.")

    # <<< The rest of your logic now iterates over the targeted files >>>
    for file_path in files_to_process:
        if subject_program == 'CALC':
            # Assuming this function exists and modifies the file in place
            calc_define_missing_variables(file_path)
        # elif subject_program == 'basic':
        #     # Assuming this function exists and modifies the file in place
        #     # basic_define_missing_variables(file_path)


def extract_exception(stderr, stdout=None):
    """
    Extracts exception messages from stderr or stdout.

    Returns the full first line of any known exception or error.
    """

    def decode_output(output):
        return output.decode('utf-8') if isinstance(output, bytes) else output

    stderr_decoded = decode_output(stderr)
    stdout_decoded = decode_output(stdout) if stdout else ""

    # Prefer stderr
    for line in stderr_decoded.splitlines():
        line = line.strip()
        if "Exception" in line or "Error" in line:
            return line

    # Fall back to stdout (for interpreters that write exceptions to stdout)
    for line in stdout_decoded.splitlines():
        line = line.strip()
        if "Exception" in line or "Error" in line:
            return line

    return "<no_exception>"


def clear_directory(directory):
    """
    :param directory: we want to clear the directory so that we can write again new files
    :return:
    """
    # Check if the directory exists
    if not os.path.exists(directory):
        print(f"The directory {directory} does not exist.")
        return

    # Remove all files in the directory
    for filename in os.listdir(directory):
        file_path = os.path.join(directory, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print(f"Failed to delete {file_path}. Reason: {e}")


def save_to_csv(unique_profiles, output_filename):
    """
    Save the list of unique coverage profiles to a CSV file.

    :param unique_profiles: List of tuples containing unique identifier and the coverage profile.
    :param output_filename: Name of the file to save the CSV result.
    """
    with open(output_filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['Profile ID', 'Coverage Data'])  # Writing header row
        for profile_id, coverage_data in unique_profiles:
            writer.writerow([profile_id, ','.join(map(str, coverage_data))])
            # writer.writerow([profile_id, coverage_data])


def get_fraction_value(fraction_str):
    """
        Convert a fraction string (e.g., '2/3') to its float equivalent.

        Args:
            fraction_str: A string representing a fraction.

        Returns:
            The float value of the fraction.
        """
    numerator, denominator = map(int, fraction_str.split('/'))
    return numerator / denominator


def calculate_rse(mean, std_dev, n):
    """
    Relative Standard Error (RSE).
    """
    rse = (std_dev / (mean * math.sqrt(n)))
    return rse

def extract_exception_type(exception_msg):
    if not exception_msg or exception_msg.strip().lower() in ["<no_exception>", "no exceptions occurred."]:
        return "<no_exception>"

    if exception_msg.strip().lower() == "<timeout>":
        return "<timeout>"

    for line in exception_msg.strip().splitlines():
        line = line.strip()
        lower_line = line.lower()
        if line.startswith("java.") or "exception" in lower_line or "error" in lower_line:
            exception_type = line.split(":")[0].strip()
            return exception_type.split(".")[-1].lower()

    return "<unknown_exception>"

def setup_logger():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        handlers=[logging.StreamHandler()]
    )
    return logging.getLogger(__name__)

import os
import shutil

def clean_directories(subject_program: str):
    """
    Remove previously generated folders for the subject program.
    Creates new empty directories with the subject name in uppercase.
    Used for artifact reproducibility and fresh reruns.
    """
    subject_upper = subject_program.upper()

    dirs_to_clean = [
        f"./GENERATED_INPUTS/FUZZ_TOOL_SELECTOR/{subject_upper}",
        f"./COVERAGE_REPORTS/{subject_upper}",
    ]

    for d in dirs_to_clean:
        if os.path.exists(d):
            shutil.rmtree(d)
            print(f"[CLEAN] Removed old directory: {d}")
        os.makedirs(d, exist_ok=True)
        print(f"[INIT] Created clean directory: {d}")


